### ISSUE TITLE
ValueError: zerro length field name in format

### ISSUE THREAD

**Issue by ScottBrenner** [asobti/listentothis#1]
Trying to run ` python listentothis.py --subreddit listentothis --period week --playlist-id <playlist> --spotify-client-id <id> --spotify-client-secret <secret> --refresh-token-file <file> --search-threshold 0.1` 
but am seeing
```
listentothis/reddit.py:1: DeprecationWarning: the sets module is deprecated
  from sets import Set
Traceback (most recent call last):
  File "listentothis.py", line 135, in <module>
    sys.exit(main())
  File "listentothis.py", line 85, in main
    info('Fecthing threads from Reddit')
  File "listentothis.py", line 22, in info
    print '[INFO ] {}'.format(str(msg).encode('utf-8'))
ValueError: zero length field name in format
```
Any ideas?

**Comment by ScottBrenner** [comment]
Was an issue with Python 2.6, working on 2.7.
